version: '3.8'

services:
 db:
  build:
    context: ""
    dockerfile: Dockerfile_db
  image: sq_db
  ports:
    - "5432:5432"
  env_file:
    - ../../.envs/local/.secrets
    - ../../.envs/local/.vars
